import faiss
import numpy as np
import os
import tiktoken
from sentence_transformers import SentenceTransformer
from pytube import YouTube
from youtube_transcript_api import YouTubeTranscriptApi
import math
import spacy

DB_PATH = "highlight_vectors.faiss"

def split_text_tokens(text, min_chunk=125, max_chunk=150, encoding_name="cl100k_base"):
    encoding = tiktoken.get_encoding(encoding_name)
    tokens = encoding.encode(text)
    total_tokens = len(tokens)
    if total_tokens <= max_chunk:
        return [text]
    target_chunk = (min_chunk + max_chunk) // 2
    num_chunks = math.ceil(total_tokens / target_chunk)
    base_size = total_tokens // num_chunks
    remainder = total_tokens % num_chunks
    
    chunks = []
    start = 0
    for i in range(num_chunks):
        current_chunk_size = base_size + (1 if i < remainder else 0)
        chunk_tokens = tokens[start:start + current_chunk_size]
        chunk_text = encoding.decode(chunk_tokens)
        chunks.append(chunk_text)
        start += current_chunk_size
    return chunks

model = SentenceTransformer("all-MiniLM-L6-v2")

def vectorize_text(text):
    embedding = model.encode(text)
    return embedding

def get_transcript(video_url):
    try:
        yt = YouTube(video_url)
        video_id = yt.video_id
        transcript = YouTubeTranscriptApi.get_transcript(video_id)
        full_transcript = ' '.join(entry['text'] for entry in transcript)
        full_transcript = ' '.join(full_transcript.split())

        return full_transcript
    except Exception as e:
        return f"Error retrieving transcript: {str(e)}"

highlight_texts = [
    "we pass ca n't go upstate let 's use this watch this this ball watch I want to go higher good this is the reversal of fortune first tries to test a oh my goodness and they just left back up and he says you know what this is Island getting a trap at the top of the circle and they blind sizing from the right corner first to 's first present I need to see that again cuz I do n't think what he did while watch the extension of the",
    "body how about that now that that 's always was a shock that was just a great grateful the belt the building was standing in true appreciation goodness can you believe that five seconds pirates tie week the just attack the basket catches puts up the play but the officials are going to review the same availables be mine with the huge offensive rebound I lose it right now let 's go home reverse 360 going again that is unbelievable this building just exploded they occurred an injury dealing with weights in the weight room so he stitched up and the left hand doing all this",
    "the judges are coming over the table to congratulate fitzmartin this is unheard of all right with his first album final round ladies wait get that ticket timeout I saw him rubbing his upper lobe now I was wondering what he was doing he was just cleaning it off making sure there 's nothing slippery there because he knew how far did the rim he was going Harvard then have you ever seen that I 've never seen that before I 'm not sure the guy came into the room gross misses another Smith has it down three should the foul no for trade that one goes down the game is tied - or three - pointer way off the mark tips it",
    "out again will we set down by two not calling timeout and I like that move in the hands of for a point two remaining young lady whooping fives rose trying to get open fires away okay off balance Oh give me a basketball the 20 year old comes flying through the air parent South Florida and gives the King still a hammers it down bogey steps away pomp balance goes up the air buh - bye good will throw in the shard lowest play off the ball gets it to and curry when I was serving puts it up the by three Irving raises up",
    "contested three is up a good for he 's five of six behind the orchid that 's - and here we go here we go PG yeah oh yeah PG that is the one ask my question look at this again I mean that 's slam dunk competition in a game they do have a timeout decide not to use a curry cookery with 62 second remaining Rize the NBA record with his twelfth three - pointer of the game here comes almost a sheepish grin understand I want to see it again this could be as good as anyone we solve for plate tonight patient good defects wave from",
    "behind takes it away Chalmers pull and a technical foul called on with its cost now quickly that changes out now it puts a pressure on the the score once again Jordan with 43 stealing care from 17 seconds 17 seconds from Game seven or from championship number six short open chick combo with the lead it's time out 5.2 seconds left Michael Jordan running on fused with 45 points ball against Westbrook is green from Jordans they're not calling anything that they're really letting them play it's a physical game",
    "oh what a play by is it possible to top what he did last year almost Amash gone it 's better than a Mozgov I did n't think it was possible to top him look at that play when it comes out on the ground now they switch in his piss again a spit screen they win and now that only may be making its way has to be a factor look out out of my er on the pic this is good if it goes Hey can you have a better city quick stuff throw one up the guys wo n't even shoot that Green",
    "whoosh bang - will be aware that they give it back to - all over him with the help takes it to the basket dunk in a three - pointer was told very looking for wave denies it in the with 10 with 8 with 6 not a good matchup right here for the nee - sama is waiting for the steal the tune Wade puts it up for the win and the full rebounder an incredible opportunity there are ads for three it 's good",
    "from down town right there those so gifted comes down and just pulls up and knocks it in but at the other end they had to get the two - for - one and then they had to file the moment it hit dream on when you 're shooting a basketball for shooters are really for anyone so you kind of see how it 's affecting we just with the time running down just took flight off Georgia Hill took it in the chest went up a couple more feet with the finish here in there 's bird with the ball against my home it 's blast and see sting hit it off of a",
    "player no it is here 's a disparity in the call they 're going to give the ball to well the first day that 's part of his game as the decisions that he 's making tonight when to shoot and when to pass again Alonzo Mourning changing a shot this lead of a lamby 's largest of the game but talk about large how about that slam dunk from what body control and what power by this six and a half to play in the third Toby again is move around Bo Peep trying to put them up finally shoots will be with it now lead 105 96 another day for away from Belgium Baylor 's",
    "major record for the night at least this would be 18 for $ 20 eighty one point game 55 in the second hand ladies and gentlemen you have witnessed the second greatest story two one they counted elevation we ca n't hold you hold your breath till they start down then it can begin he 's got it I 'll be wondering what the NBA record is for most points in a corner he had just watched it anther and klay Thompson passed 15 and 37 in a quarter for the times they 're shot against",
    "and stolen by other place the fans got what they wanted hey locks against adjourn to the circle puts the shop the sixes kept it alive again did n't the other dead I was born into it fully never seen that play the game of basketball I played again fast because I love it and you know the MVP stuff that 's well you know it 's a fast break to himself and even the only one to do which come in look at him go through four or five guys and posters is trying to press pressure the inbounds pass and it comes into old",
    "with ten seconds - showing in the clock eight seconds left to go on the clock seven six five the bushy shirts two seconds one second yes close it up made from the other side of the big seven shut down no go Tonio laser movement ball tipped out straight on three to timeout they put on in this possession seven to shoot Nowitzki drives with it a deep lefty layup banks it in with three point six remaining out of timeouts",
    "trailing by two back to way way puts it up for the win off the mark and 's tie the finals with one of the most incredible comebacks in NBA Finals history a great game and I love down the stretch they put the ball in their best players hands and did not settle for jump shot floor at the Garden in consoled by his close friend still trying to cope with the tragic loss of his 22 - year old sister just yesterday they had a moment of silence here at the garden and tears streaming down the face of he will play and moments ago he was introduced to the home crowd",
    "and had closing out I 'm paying about a 29th footer time a basket equals a 50 - point games attorney I am having a third loan have you never seen to get tired corner of the team he 's done we 'll be with the ball and the linkers downfall on its way but he continues to leave the ball with half a minute to play bright for the he is fouled but if he have enough colege the get free - throws will save two free - throws per 60 a 60 point game final seconds here at Oracle Arena",
    "it 's official number 73 the greatest regular season in NBA history now belongs to the is hurt down on the court underneath the basket I could n't tell what happened and this is a tough one holding his right ankle my captain our the trainer is with him and and the are going to have to call a timeout because started to get up he got up and then went down on the floor then I say is coming back in the ballgame it 's been the show plus an injury to here in the third off balance basket counts and a foul",
    "as he goes into the first row and he is still limping he is a game performer he 's got to be hurting and limping and he continues to put the points on the board for has put on a brilliant exhibition of shooting this ankle injury in this third quarter he has been a one - man gang dream attempt remaining in this period and a looper 's shooting eyes still on he has 16 points in the corner 28 in the game yeah but he 's limping noticeably right now and coming period he has 35 in the game 23 in this period can you imagine the great performance maybe one of the best we 've ever seen in",
    "one quarter in NBA Finals history our test looking gets you the pride fly until you has to put up with the buzzer hit traffic touch bro inbound at half - court to the NBA Finals moment ever break down defensively nobody stays with has to come out coming up on a minute remaining here in Game five Pierce four three let 's go pairs from way downtown then leads by four big three - pointers here the fourth quarter gets it the Oakley Park by bounces Meyers cross - court sca",
    "comes the plane is there a foul on the play no it but the passion look at the animation on normally sweep the eye very smooth you do n't see this kind of energy and passion aldridge talked about hits playoff time look at the extension Sean itself let me give you a little quote that goes by six kevin is asleep check if he 's hurt check if he 's here he 's hurt not showing his feelings are hurt down - low predominate baseline drive that fantastic all control good rebound nice outlet on the",
    "run two on one three the finish because been to make that a mobile pitch and finished he caught it watered down way up and down knocked away in stolen years trailing the lock double team three on the 24 - second clock it 's going away from and Payton safely Sonic 's baton saving the ball did he get it yes he does right into his teammate we 'll take another look at what a play by copy pasted some lettuces improve pass in the empty over there very close to a five - second count at the buzzer and the defeat",
    "The are waiting on what the ruling on the floor is a made basket by again chef championship round in the Verizon slant on those honey want on these this is real this is real okay this is real this is real okay Zach said that 's it but we 'll just to say f9 that 's not so good it was n't ten the dinosaur Play you can go to Orlando Florida that might be helpful Peyton in that mascot my god let 's go home let 's go",
    "that 's pretty bad I can't I just do n't know man wait wait wait let me see like that solve in Arizona I saw him in there but I do n't I do n't see this well that 's why I picked them kidding man always this is a time this is a time you do n't know what you saw if you see it in slow motion hey man you would know what you just saw a man you would know what you just saw bring in the ball no watch out lowly breathing a bit behind his head first he",
    "cocked it behind his head like he was going to tomahawk yeah nobody lost them that was an incredible display shooting Wow was turned off but whether what he 's going to try to do is blow out the candle as he dunks are you kidding me you gon na do is make a mess hey remember the last two years of the slam dunk when we said that slam dunk contest was back yep look this is what we 're talking about validating it right now right now he 's gon na blow to kill if he blows the candle out you got ta give away he 's only us at TT hazard now he goes up then it 's",
    "still out he takes the ball he could jump over he said again if he can jump over suit than I had to get on my feet the world man changing with it come on seriously if he can jump on my seat man come on to the side look at the run look at the left hand pretty good right it 's good okay I told you ja wohl it 's gon na get it dance it out baby dance it out rock it out yeah I was upset he did n't get at that time and Grady bumps for his name said coming over that 's a clean block block it kitchen",
    "after the fact the jog out to to pull - up jump shot back to whoa coach rebound now the next will hold it for the final shot as a 24 - second clock is shut off Mike day 21 timeout and let the set up the D the crowd on its feet here at the Air Canada Centre they had the down with the dagger and now shop Westbrook call the depot single to inbound grant and on the floor for the flutters out of timeouts Adams gives it back to raw speed shy historic day all I can say is why not 22 triple doubles on the",
    "season and he is the ball game like that turn best in the league and finishing 207 three now you see me simply a spectacular move by flash here 's drives past Bentley he blocked me jumpshot in the guard all five nine of them that 's what it was with the against the with this one against the four - time MVP post a hammer good job baby got the rebound Rose it out to pole sitter we said no believe that fortunate you",
    "know shot up the shot clocks it 'll reset and head reset was that is gon na be crazy I like this oh you got it there 's the switcheroo desire now watch come into the picture though he 's got time something 's with 67 points with 645 remaining Tatum drives down that strong sit down Wow so he finishes it and then he goes right up to him a thorough rookie with 24 was on him their best defender will see how the plan Sefolosha throw in when he gets his",
    "legs into his shot his mechanics are excellent right oh my goodness diving stop by letter / play / play all my goodness what a tremendous play did not give up on a play chases him off the line I was alter the shot shot blocking his gotten so much better 's top job but he makes the 's playing well for 21 points for belly last night playing really well for the temple walls in the starting not here tonight is that perfect though lovely I need more cowbell but the anchorman as well in that vault lobs to the way the tip walls all fences 's they 've got a chance to hook that here that",
    "cryptonite gets inside puts up with tough shot and hits it anyway forty eggs fifteen a half a century for here tonight to have a game like this 50 points against a good team three no long rebound tracked down by Rubio Engels will fire for three that wo n't drop another rebound has it blocked in the corner by who else tell it 2011 MVP rose and everybody just streams out on the floor to greet him showing the respect they 're called anthem ants mice got the double ticket touji like playing against the curry has not scored in this game his first basket sit straight 47:44 he 's",
    "like no and he hits another long ball that 's his fourth of the first half here comes Collison kinks out well turn this breakfast systems on Oh Bree Casspi is on fire and again the can't come up with a rebound and it 's right in their midst and a custom pretty boy Wow how does that happen Porsches too many shots now I really have a good chance to pick it out there 403 by step and it 's fifty three fifty there 's a heatset people coming over test me oh boy he has now made six threes and eight fries and it 's 5650 he 's got 23 here in the half",
    "did try to answer back like NBA basketball here 's test me why not he 's got smoked took it off his fingertips overreach me let him bat it back when it 's curved Tori have to crawl see and getting the basketball because a lot of good things will happen that just was n't scoring in downtown in a different way to score coming off baselines man oh he does it again throws it right up on the rim comes flying in from the right corner and another dunk it was a dunk athan Friday night they 're starting it again here this afternoon boy left wide open incredible rebound put back glass goes Wow",
    "poor pal huh now in the rage close to the screen t - man ripman explodes on the nice pass by Butler slow rotation by and if because if Griffin is able to get to that launching and got down there to tell as a set it stayed off that rim but he was Hornswoggle befuddled c.j but countless season - high with 32 and the leave it by 14 19 in the corner from our largest lead here of the night I do n't feel right watching this I do n't feel right watching it and enjoying this that is inhumane in the",
    "ins frantic video by one of mine he stopped about three feet short of the rim and just threw it down that is amazing he never touched the rim with his hands oh my lit up with just got the kid who 's the piece big old black by all of them Parker the Neal for the shoot marking homes read the beat all of Blackford throws it back it 's ready to dunk here here in Game two and here one of the great blocks you will ever see splitter winding up to throw it down and the strength of to stop this and throw it back exquisite timing on his back how did",
    "he see him there well his name is that 's why coming off here by one gets it into howís on the drive nearly lost its still juggling Parker with two to shoot just gets it off the time any banks a man what a shot from Parker stink 2.6 seconds to go now late Griffin will turn there here it is again we 're gon na watch it right Griffin oh he steps behind holy sculpture becoming something very very special with the fake what a beauty and Rashid from long way",
    "it 's across the lane where their eyes are always looking around this a nice lunge and steel bike puntas selected this young man with the fourth overall pick the nice little spin move and finish in transition here he 's a work in progress and needs to put on some weight that was up that pass to the most high Jordan gets the step on down so first offensive rebounds two waves finding an open area inside drives hard draws terrific now watch how he splits the seam of the zone all right and then he comes right up there saying moving underneath on the shot and then the finish how about the finish",
    "a flip back with the English on the on the spin of the ball cargo exploded showcasing a little bit of everything and then some feedback the man I saw a plea lane to the basket so I was going to dunk the ball I exposed the ball but then I saw long arm there and it was just instinct to change it I changed it to my left hand and with able get it off Partin just crossed over West Johnson take a look me to have this man down this can go up 14 Jordan oh yes yes yes six points for came back Nikki out with a nice boom six tenths of a second ransom over",
    "Gaza nice that 's it 's buries a three out of the corner can you believe that since the feet left his hands before the clock struck double zero crossover into a and when you 've got ta come in oh my goodness we talked about the struggles of Mitchell shooting the basketball but he we 've lost the handle pops it up right - crisis over loses dragged into the lane 's the hymen off the window up and end what a move by past records suddenly caught me looking lemon biceps elosha just would n't quite fall now here 's the other",
    "the word bull Wow terrific game for Crawford and they take the lead he 's got 15 points no luck Rondo behind the back for two put it in the pot baby put it on the real foul to give for 9/10 left of three wins the series its lured he got the shut off for the first time 814 because it goes in at triple zero but it 's out it 's over and the Strip a one - point game welcome to tippet with the sale here they go they get it to Fisher the buzzer",
    "it 'll have to be reviewed they 'll review it they 'll review it it 's also it 's so close very close what 's the Louisville has to be out of his hands both it 's out of his hands it 's out of his hands Wow that 's good ready five seconds to go continues to hint at the line my SEP with a quick jog going is all over the Grady I was picked up and ca n't find anybody they have no timeouts when finally gets it in to the grading eleven yelling on the inbounds rata make things difficult for fire he gets it in we which is felt on",
    "the floor and it took approximately here 's Iverson move it offender stays right where the wants to go watch the baseline nine in a row seven straight points five give a for some survived Caritas behind it 's the largest that could be the greatest move I 've ever seen that no I 'm being serious watch his head coach no we 're gon na show the reaction of as this play was developing for somebody else if you make a move with him right now to try and get they probably could use like their athletic shot clock",
    "takes it now is like a poker there but among games the flute played it just 16 seconds left to play Derek one - on - one at the top starts he just crossed over watch this watch ca n't get up bobbin and I ca n't get up turning around and around like a top st . playing on the show won again by Stevie franchise slight jabbar slight jump hook to wrap right around Kathir he looks like urban and this was more like a nice man move right here I do n't know somehow kisses it off the glass a little top loses it all right go visit",
    "perfect last - second decides to go over some people to come over tonight we love it he 's got 13 and a chance for a three - point play well we 're down at ten seconds remaining in overtime and has the ball again guarded by the fadeaway it 's just different than East up to point please as we see takes the anyway have to push it look for the pick - and - roll is someone to the corner not a seven - second there 's a doctor stuck here 's a welcome eople the need a 3 - 2 win 10 seconds",
    "1 raid against Iguodala 5 seconds well waiters back to twin shoots no I could n't get it off now fires it up 1:26 go to 20 just happens gon na count it up in time let 's take a closer look here on your street totally off Baptist pufta class circus shot and weighed the hero once again and bragged to his coach about taking MJ and know he 'd finally get his chance when I grabbed a ball I heard yell I gave him a little cross to see what he bite on him I let him set his feet then I stabbed it back again",
    "behind the back steps back Mor ball fake oh oh my gosh people watch millions and millions are going to watch this also has baz on him what was that way they wanted to look at this look at the dance right here T 's like okay will you shoot I 'm tired of getting embarrassed on the perimeter runs into Luca LCA on the floor FS Fant what way to finish that hustle play on a platter for to climb the ladder but with a turnover nasty I mean that 's all you can say about it and shaking up and I think also walking to the locker room",
    "hurt himself he 's holding the right forearm doin will defend a screen by the switch to rivaly three C oh oh run here he got the switch that he wanted he got Lively dancing te 109 the foul called to a minute 10 to go timer is down to five donic ca n't find any Space 3 seconds two deep one donic oh my gosh boo gets it back dodic Dums inside puts it in two seconds left the are out of timeouts they have to go 94 ft stru from midc Court oh oh do you believe this wa to take a shot of this James against Porter Drive Spence gets inside it",
    "good it 's 40,000 for the NBA 's alltime leading score with another Milestone as the legend of continues to grow Mor off the bounds 360 spin in the Finish oh he did that oh no 360 spin and a finish for morand spins and hits again I 'm morand you run out of words to describe what he can do go for the crank and then spins off the back iron and off Horford into Victory he 's ahead of the pack he just puts it over there White 's head and he throws it down like he was teasing him with the ball he did he held it up there like he was playing",
    "against sixth graders rebound of Del r del r eight points in 13 minutes hero for Caleb by that pitch ahead pass to Tyler hero one fake two fake drop off D behind both Dam and CJ here he comes up the floor his rookie ear he had just 10 threes oh 8year Pro watch this one oh man you know got to be strategic you only get six so that 's it KD with a crossover Glides right to the basket just how quickly he gets off the ground I mean there 's so many aspects lobing it up oh my giving a highlight to remember oh like that shot clock about to expire that 's able to track down",
    "long rebound and Simmons Simmons misses the bunny and the older son made it right back the younger son through his leg H behind his back like that like that how about about that pis bringing the house down okay T wow fun game here in the Twin Cities look at the moves by swash and slamming are you kidding me man play it 's loose has got it Brunson from behind yanis wow dropping in the sledgehammer and took one dribble from gets it into capella hand off to tre 's going to back it out we 're down to 16 trying to win it not give the a chance back to back to",
    "he 'll take the three b game backing it out wanted to work some clock covered up by got it right back to it and drills the biggest shot of the night shot clock game clock shot clock down to five here 's towns from three it 's gone towns with the dagger 3point field goal and an it 's lead by five 36 a minute remaining in this game Luca gets through the Defenders Powers up score it 72 for number 77 once he split the D it was all over I love it do n't call it tie ball game worst can happen we go to overtime makes a move d the have won 5 Seconds to",
    "work with even at 90 from Freemont yes sir pick and rolls as well and this is the shot it 's a few steps Beyond half court but he 's got that type of range he is one of one time here 2.8 It 's Quickly in to and he got it away from about 40 ft he made it he made it he made it a little something for Slovenian Heritage night Morant trying to feed it ball to the floor job from the seat of his pants L look at thisle he 's waiting he 's waiting for the right pass 5.2 left no timeouts left for the buks Here 3 seconds D PS for the",
    "time is alive Dame time gety looking looking inside the pass jump shot is up it 's good with 1.8 remaining G as it and the go up by one get some points out of this oh gy from the back side he was on his back still get the shot up to beat the scrip on from down 15 to in front by 14 and ding in the P spectacular stop it stop it two and look at them guard one another trying to poke it away uh - oh uhoh wa right back right did n't I say you learned it for me you watched The Telecast oh and",
    "with the steal here at 3/4 cour has it clock ticks got to put one up yic for the win in your best players hands I just told it was a great play call nice quter at the other end and he tries and he gets it to go beating the clock cord length that 's intercepted good at the go he 's got it got it got it a big time three oh what a shot right when had this in single digits and in those six wins he 's averaging 37 a game he 's got 35 now oh no no no no no no you got to go he 's he 's this is about as H as",
    "we 've seen no way it 's like a game of horse out there no way and in for for the win oh my a southp finish from just absurd T to shoot oh a signature slam now mbid takes on hardenstein Maxi for three he got it Tyrese Maxi out of the pack T chenzo finds great defense here by the Sixers wison gets a prayer of a bounce two - point game Maxi hits the deck hard takes it from him shot clock is off D chenzo no hardenstein with an offensive rebound another chance here chenzo he 's got it the have the lead again",
    "out and running L for and even cam reddish was here LCA for three for three and lead almost lost the handle kcp falling off the cliff turn it over Tatum on the move oh he set off the smoke detector t spins it up no batt it off of the rim here go the 6 seconds to go he 's scores with 3.8 and has the lead that was sketchy there the ball was on five fouls so 's going to have a go right at him wow exquisit that 's incredible nobody in this game can do the special thing and",
    "my goodness it down on him and he 's going to get called for tating taunting after stuffed when he played for the Sixers that knocked us out of the playing game right yep oh Wy nice touch as he rolls it off the iron and good he 's having himself quite a game right now Focus cuz we got too hung up in the officials he talked about some immaturity oh DK Jones D that gets the crowd fired up he throws it down shot clock is off wiama goes right by Durant with the left hand oh look at and look at 's face gets past lard with seven floer good gives the a one - point",
    "lead with 5.9 remaining AG a lot of guys on the executive committee are deeper in their careers they 're in their 30s but to see Jared whoa with the dunk against canar a catch and shoot California a sord tops twin brother of a men Thompson what a move oh Duncan Robinson a screw ball for the layup what a dribble move get that reverse great y Steel by sus he 's got with the one - handed dun that brings the clowd to its feet six Reeves going behind the back spinning away from the glofin the crowd loves it Reeves putting on a show with the fancy dribble",
    "luck down to five got he was close to it chance for the last shot goodness but right here have you ever seen a a live dead body there 's one right there green isoing green driving Green dunking to five Klay tops it at three clay for the win good I told you play is still out there if you want to take step away they got another killer advantage oh my blocked by Wy Again by Wy get it out of here P the ball on the drive and he 's fouled landale Point landale leads the break here 's the lob and that time actually he gets a bit of that it goes up the backboard",
    "and jayen 18 points for sharp and the C out is 1054 99 but just for a moment as shark goes back so far tap by D going to give it up throw it down little Showtime ah that was nice LeBron Taps it gives it to B head oh my God denied by foxy in trans theck connection oh my God this build getting some early minutes here on the floor as well and pal open Luca donic with a little spice 4 seconds got it from CBA again late in the clock in desperation he faks it up is luk right there I got to go so a",
    "new lineup Dr in the steel oh the big cat take it time big cat oh Dr in crossed over Chad wait T shoes CH T you shoes the big cat with the crossover woohoooo oh he's got the everything oh my goodness no no no he made it he CED and made it on a tough turnar around Demar D roen gets it Baseline and is able to knock it down Chris and we go to over defense forcing the Miss and the crossover winding up and brings the boom on one 6 seconds two seconds 1.2 on the clock  for the two-point lead blocked by Victor got be",
    "another word for that one destroyed oh mama talk about destroy vict for w Yama what the and in those six wins he 's averaging 37 a game he 's got 35 now oh no no no no no no you got to go he 's he 's this is about as no way seen no way no way it 's like a game of horse out there no way and knocked down against durin loose ball to duumu shot clock down to two D Ro in it the marvelous the rose and finest with some Hang Time defensive players as far as stealing the basketball in the league oh seaka one hand Rising jam and he knocks down two leg Brandon vill with a move",
    "and throws it down man we are seeing some offense here yeah when you talk about oh nice finish a poster from o and the foul but they are shorthanded and it has been a rough season a drops bade and hits the jumper that was a beautiful to TI again big to play big big time plays turn the AC up cuz he 's hot up against Brooks goes away from the pick we his way to the C in the hole on that 's a poster Here G screen domas give me that the hammer yeah yeah de Joe and hren The Most Dangerous Ones gidy looking looking hen 's got",
    "it turns fires he hit it he was on the line though I think he might have been on the line so it went to 0 they got to review it it automatically goes to review they have to get this ball inbounded they 're out of timeouts they throw it to grant grant runs up for three look at it tight up and he baked it in he banked it in oh God you saw that coming dick Life Special wow got it back and that Home Three what what was that three he trying to find zubot such good play by ad train down the track look out bling foul that 's a three - point attempt Look Out Below look get on top of",
    "a good Outlet goes to oh what a play by do oh now you see it now you do n't put a little get some points out of this oh gy from the back side he was on his back still gets the shot up to beat the two and look at them guard one another trying to poke it away wa right back right did n't I say that pops upset vel 's going to have to go on his own three - pointer no good eight to go you might want to call a timeout to advance it takes it from him hangs yes and the have the lead a lot pressur it a three will tie",
    "it and hand off to Luca back to XOne got they did it they did it the basket he throws it up and misses tapped around it 's loci and they 're going to get control of it oh thebr look out game over wow you see that speed he thought he was F seaka makes the catch goes to knin boy the pace will somehow hang on on it oh turns into a dunk by Turner and gets called for the block and Turner has a chance for the three - point play 71 % as mentioned and you have players like Ingram no be with the throw down he had this that I mean there 's so many aspects",
    "up oh my giving a highlight to remember this draft you decide not to look for somebody that as leer really wants to show this so we 're going to do it right here watch it between the legs in the slam dunk guys though win or lose oh over Victor wama to joic from the free throw line has it 5 Seconds To Go deatte gram yes get it 's a good one back to on the drive puts up a three oh he puts it in with and you see well I got to get it off just throw it up there same spot that missed the other night here the fourth quarter yeah",
    "have came into this game the other way and reads in the way oh what a pass what a watch this pass this is unbelievable one two three five Defenders look at that that 's amazing runs into on the floor finds KY re fastic what a way to finish that hustle play on a platter for to climb the ladder but after KY looking looking inside the pass jump shot is up it 's good with 1.8 remaining gildas it and the go up by one right in front of their bench AB going Coast to Coast they 'll throw up a prayer got it wow what a game",
    "so y they got to be careful here these guys dis is switching now you can garish the sky hook which so rare players do it but now we got Fox on the break Fox pick 's pocket and got this low block he 'll come off a yanis screen and get it near Mid court with 5 Seconds lard step back blocked by did winning loose ball game over huge win for the without and an injured they win it 1231 Wiggins with five fouls monk drives on him monk hangs and he scores what a basket monk gives the the lead it clock ticks guy to come off of the handoff",
    "dunks to the rim the shake and the bake push the shot clock is dark they 're down by two George wants it all the three oh my goodness hot damn push the out in front by one doic into hay what a pass some three go what what a pass how did he get that through all those defenders in two seconds left Butler step back for the win yes delivers the victory 118 116 here 's jayen green going oh with the left hand he 's got 24 Rocket 's down seven Trey the floor is spread it 's holiday it 's from the top good with one1 of",
    "a second and the going in front 123 to 122 I ca n't believe it point four Quinn says play on 3 seconds two for the win got it yes yes coming out of the timeout here 's white goes around the world and punches it home over white slowly breaking out four early assists billian also has four assists to the basket skies and jam nothing wrong with his knee whoa what 's wrong with his knee fine give me some tenden ntis team with a chance to win it in his return here goes he spins morance scores and the timer expires K the basket and morance wins it for the",
    "12 for oh goes back oh no and puts it down are you kidding me come on you hook again well here 's the oldest guy in the league right here spinning underneath oh a 360 oh the old man did a 360 wow could tie it with a two or win it with a three Here Comes a three for the lead he made it with two seconds left do jant puts up 109 to 108 range look how far away he is from the basket on this pullup find seaka their Leader scri by Caruso final seconds can tie it peruso for the lead turn up the",
    "a is CED here woo woo big play guarding green here 's oh what a circus move by green oh man so creative in the air oh pel just missed the steel ca n't make you pay but follows up goodness Lord that was filthy I do n't know seconds now five now four up fake from the Baseline knocks it down with who was ice cold all night just warm enough here down in Georgia turnover time taken by he 's going to go all the way and throw it down and one wow what a way to start the game for nerk with the rock finds Durant raising up for the win but watch this",
    "watch guso he made him change it in the air and then knock it down oh man two on one on the break Isaiah Joe SES it up green throws it down Harden this is for the lead oh he put it in counted at a foul oh my goodness AJ Green little tough floater oh W Andre okay did he fun game here in the Twin Cities look at the moves by swash B and slamming are you for three off the rim 6 seconds five Rosier to four Court 2 seconds one bam out of Bio from the top and he triples bam out of Bio with an improving three - point shot I think he got",
    "it away in plenty of time that was his first triple try posterized tler denied up top oh ju yes they do B look at that spinning like a top pass great finish SE Curry comes free gets the ball puts up a three - pointer B the three - pointer with 710 of a second remaining seven to shoot for to shoot gets down lets it far for the lead God damn lead by two top good comes up there to by him the pass though to intercepted oh cocking rocking and knocking it down and landed with a pose is to give a three - point lead he missed it are not going with a timeout",
    "they Advance the ball n lays it up oh man a defensive play as n was trying to get to the rim they block it wins it 113 111 the have a shot blocked at the point2 left no timeouts left for the Here Comes D 3 seconds dve PS for the Dave time is Alive and Well in oh uhoh he just lost Butler yeah green and the Look Away you 're a green oh my goodness yic has it clock ticks got to put one up yic for the win oh it 's goodone yic got it off in time and the win it are you",
    "kidding me easy CA has that tip by but dodis gets it back dodet dumps inside puts it in 2 seconds left the are out of timeouts they have to go 94 ft stru from midcourt oh do you believe this you believe that your final score here tonight your just sit back and enjoy tap another turnover for gets it back and threw it down and one from the oh my god ANS HT his hand on that too that was ridiculous IA looking in for for the win oh my oh my a southp finish from just absurd",
    "game-winning shot buzzer beater slam dunk clutch three-pointer unbelievable comeback fast break crossover dribble big block steal defensive stop transition score record-breaking epic finish spectacular play crowd erupts incredible assist jaw-dropping heroic effort highlight moment insane play posterized alley-oop deep three dagger shot putback dunk chase-down block circus shot spin move ankle breaker high-flying dunk no-look pass contested jumper last-second shot game-saving block off-the-glass pass behind-the-back pass half-court shot full-court heave heat check unstoppable run underdog story dominant performance fadeaway jumper skyhook impossible shot triple-double milestone comeback victory cold-blooded three defensive lockdown unstoppable crossover half-spin move coast-to-coast breakaway dunk step-back three Euro step monster slam dagger three poster dunk throwdown clutch steal dagger layup one-handed jam ridiculous handle hustle play game-clinching shot dagger fadeaway insane finish highlight reel crossover buzzer-beater three-pointer thunderous dunk showtime move electrifying moment spectacular",
    "block go-ahead basket game-sealing play historic performance backboard alley-oop ferocious slam in-and-out dribble dagger shot from deep unbelievable pass dominant fourth quarter hero ball big-time shot insane highlight game-changing play miracle shot unstoppable drive acrobatic finish game-tying basket deep-range bomb unbelievable hustle nasty rejection ultimate highlight game-defining moment crowd-silencing shot emphatic dunk off-balance shot high-energy sequence crazy sequence dagger from downtown power dunk last-second heroics next-level move game-saving steal mid-air adjustment high-arcing floater next-level vision court awareness electrifying sequence killer crossover dagger free throw statement play insane putback gravity-defying dunk off-the-dribble three insane and-one ridiculous save unbelievable hustle last-second tip-in clutch fadeaway dagger jumper unreal finish historic moment epic rally biggest shot in history NBA history moment goaltending controversy breakaway slam posterizer dunk next-level handles incredible finesse unreal court vision underhand scoop layup spin-cycle move ridiculous crossover triple-team finish clutch gene playoff dagger championship-winning shot clutch performer out-of-nowhere steal deep buzzer-beater incredible recovery instant classic dagger mid-range unreal putback highlight dunk historic comeback last-second hero team-carrying performance rising superstar big-time highlight season-defining moment glass-shattering dunk unexpected game-winner",
]

nlp = spacy.load("en_core_web_sm")

def remove_person_names(text: str) -> str:
    doc = nlp(text)
    person_token_indices = set()
    for ent in doc.ents:
        if ent.label_ == "PERSON":
            for token in ent:
                person_token_indices.add(token.i)
    kept_tokens = [token.text for token in doc if token.i not in person_token_indices]
    return " ".join(kept_tokens)

cleaned_texts = [remove_person_names(text) for text in highlight_texts]

for i, (original, cleaned) in enumerate(zip(highlight_texts, cleaned_texts), start=1):
    print(f"--- Original #{i} ---")
    print(original)
    print(f"--- Cleaned #{i} ---")
    print(cleaned)
    print()

highlight_embeddings = np.array([model.encode(text) for text in highlight_texts]).astype("float32")
print("Done encoding")

index = faiss.IndexFlatL2(384)
index.add(highlight_embeddings)

# Save the FAISS index for future use
faiss.write_index(index, DB_PATH)

print(f"Successfully stored {len(highlight_texts)} highlight embeddings in FAISS!")

import faiss

DB_PATH = "highlight_vectors.faiss"

# Load the FAISS index
index = faiss.read_index(DB_PATH)

# Get the number of vectors stored
print(f"Number of stored vectors: {index.ntotal}")

def inspect_faiss_vectors(num_vectors=5):
    index = faiss.read_index(DB_PATH)
    num_stored = index.ntotal
    print(f"\nFAISS Database Loaded: {num_stored} vectors stored.")
    if num_stored == 0:
        print("⚠️ No vectors found in the FAISS database.")
        return
    num_vectors = min(num_vectors, num_stored)
    print(f"\nDisplaying the first {num_vectors} vectors:\n")
    for i in range(num_vectors):
        vector = np.zeros(index.d, dtype=np.float32)
        index.reconstruct(i, vector)
        print(f"Vector {i + 1}: {vector[:5]}]")

    print("\nVectors successfully retrieved and displayed.")