import faiss
import numpy as np
import os
import tiktoken
from sentence_transformers import SentenceTransformer
from pytube import YouTube
from youtube_transcript_api import YouTubeTranscriptApi
import math

DB_PATH = "highlight_vectors.faiss"

def split_text_tokens(text, min_chunk=125, max_chunk=150, encoding_name="cl100k_base"):
    encoding = tiktoken.get_encoding(encoding_name)
    tokens = encoding.encode(text)
    total_tokens = len(tokens)
    if total_tokens <= max_chunk:
        return [text]
    target_chunk = (min_chunk + max_chunk) // 2
    num_chunks = math.ceil(total_tokens / target_chunk)
    base_size = total_tokens // num_chunks
    remainder = total_tokens % num_chunks
    
    chunks = []
    start = 0
    for i in range(num_chunks):
        current_chunk_size = base_size + (1 if i < remainder else 0)
        chunk_tokens = tokens[start:start + current_chunk_size]
        chunk_text = encoding.decode(chunk_tokens)
        chunks.append(chunk_text)
        start += current_chunk_size
    return chunks

model = SentenceTransformer("all-MiniLM-L6-v2")

def vectorize_text(text):
    embedding = model.encode(text)
    return embedding

def get_transcript(video_url):
    try:
        yt = YouTube(video_url)
        video_id = yt.video_id
        transcript = YouTubeTranscriptApi.get_transcript(video_id)

        # ✅ Join all text into a single line
        full_transcript = ' '.join(entry['text'] for entry in transcript)

        # ✅ Remove extra spaces and newlines
        full_transcript = ' '.join(full_transcript.split())

        return full_transcript
    except Exception as e:
        return f"Error retrieving transcript: {str(e)}"

highlight_texts = [
    "we pass can't go upstate let's use this watch this this ball watch I want to go higher good Frankie this is the reversal of fortune first LeBron James tries to test Jermaine O'Neal a oh my goodness and they just left Donovan back up and he says you know what this is Jimmy G bucket Island getting a trap at the top of the circle and they blind sizing from the right corner first to Tom's first present I need to see that again cuz I don't think what he did while watch the extension of the",
    "body how about that now that that's always was a shock that was just a great grateful the belt the building was standing in true appreciation goodness can you believe that five seconds pirates tie week the Spurs just attack the basket James catches puts up the play but the officials are going to review the same availables be mine Chris Bosh with the huge offensive rebound I lose it right now let's go home reverse 360 going again that is unbelievable this building just exploded they occurred an injury dealing with weights in the weight room so he stitched up and the left hand doing all this",
    "the judges are coming over the table to congratulate fitzmartin this is unheard of all right Vince Carter with his first album final round ladies wait get that ticket timeout I saw him rubbing his upper lobe now I was wondering what he was doing he was just cleaning it off making sure there's nothing slippery there because he knew how far did the rim he was going Harvard then have you ever seen that I've never seen that before I'm not sure the guy came into the room gross misses another Smith has it Knicks down three should the Bulls foul no Anthony for trade that one goes down the game is tied - Anthony Smith or three-pointer way off the mark Chandler tips it",
    "out again Linux will we set down by two Mike Woodson not calling timeout and I like that move in the hands of Anthony Anthony for a point two remaining young lady whooping fives Rose rose trying to get open fires away [Applause] okay off balance Oh give me a basketball the 20 year old comes flying through the air parent South Florida and gives the King still a hammers it down bogey steps away pomp balance goes up the air buh-bye good mo Williams will throw in the shard lowest play off the ball Lewis gets it to Lacroix [Applause] Irving and curry when I was serving puts it up the Cavaliers by three Irving raises up",
    "contested three is up a good for Kyrie Irving he's five of six behind the orchid that's Neil - and here we go here we go PG yeah oh yeah PG that is the one ask my question look at this again I mean that's slam dunk competition in a game they do have a timeout decide not to use a curry [Applause] cookery with 62 second remaining [Applause] Rize the NBA record with his twelfth three-pointer of the game here comes Chris Paul [Applause] almost a sheepish grin understand I want to see it again this could be as good as anyone we solve for plate tonight patient Terry good defects wave from",
    "behind takes it away Chalmers pull [Applause] and a technical foul called on Miami with its cost now quickly that changes out now it puts a pressure on the Jazz the score once again Jordan with 43 [Applause] [Music] [Applause] [Music] [Applause] stealing care from Chicago 17 seconds 17 seconds from Game seven or from championship number six short open chick combo with the lead it's time out Utah 5.2 seconds left Michael Jordan running on fused with 45 points ball against Westbrook is green from Jordans they're not calling anything that they're really letting them play it's a physical game",
    "oh what a play by Blake is it possible to top what he did last year almost Amash gone it's better than a Mozgov I didn't think it was possible to top him look at that play when it comes out on the ground now they switch in his piss again a spit screen [Applause] they win and now that only may be making its way has to be a factor look out out of my er on the pic this is good if it goes [Applause] Hey [Applause] can you have a better city quick stuff Stoudemire throw one up the guys won't even shoot that Green",
    "whoosh bang - Raja Bell will be aware that they give it back to Ginobili - all over him O'Neal with the help takes it to the basket dunk in a three-pointer [Applause] [Music] [Applause] [Music] Cooper was told [Applause] very [Applause] looking for Rose wave denies it in the Solomons with 10 with 8 with 6 not a good matchup right here for the nee-sama is waiting for the steal the tune Wade puts it up for the win [Applause] and Jenna the full rebounder an incredible opportunity there are ads for three it's good Kevin Durant",
    "from town town right there Kevin Durant those so gifted comes down and just pulls up and knocks it in but at the other end they had to get the two-for-one and then they had to file the moment it hit dream on [Applause] [Music] [Applause] when you're shooting a basketball for shooters are really for anyone so you kind of see how it's affecting Tony Parker we just with the time running down just took flight off Georgia Hill took it in the chest went up a couple more feet with the finish here in Denver there's bird with the ball against my home [Applause] it's blast and see sting hit it off of a Detroit",
    "player no no it is here's a disparity in the call they're going to give the ball to Detroit [Applause] well the first day that's part of his game as the decisions that he's making tonight when to shoot and when to pass again Alonzo Mourning changing a shot this lead of a lamby's largest of the game but talk about large how about that slam dunk from Vince Carter what body control and what power by Carter this six and a half to play in the third Toby again is Toby Donna move around Bo Peep trying to put them up finally shoots will be with it now Lakers lead 105 96 another day for away from Belgium Baylor's",
    "major record for the night at least this would be 18 for $20 eighty one point game 55 in the second hand ladies and gentlemen you have witnessed the second greatest story [Applause] [Applause] two one they counted elevation we can't hold you hold your breath till they start down [Applause] then it can begin he's got it [Music] [Applause] I'll be wondering what the NBA record is for most points in a corner he had just watched it George Gervin anther and klay Thompson passed 15 and 37 in a quarter for the times they're shot against",
    "and stolen by other place the fans got what they wanted hey locks against adjourn to the circle puts the shop [Applause] [Music] [Applause] [Applause] the sixes kept it alive again didn't the other dead I was born into it fully [Music] never seen that play the game of basketball I played again fast because I love it and you know the MVP stuff that's [Applause] well you know it's a fast break to himself and even the only one to do which come in look at him go through four or five guys and posters Jordan Lake is trying to press pressure the inbounds pass and it comes into old",
    "Frazier with ten seconds - showing in the clock eight seconds left to go on the clock seven six five the bushy shirts two seconds one second yes close it up jerry west made from the other side of the big seven [Music] [Applause] shut up no go Tonio laser movement ball tipped out DeLorean straight on three [Music] to Boston [Applause] timeout [Applause] [Music] [Applause] [Applause] they put Bosh on Nowitzki in this possession seven to shoot Nowitzki drives with it a deep lefty layup banks it in with three point six remaining Miami out of timeouts",
    "trailing by two James back to way way puts it up for the win off the mark and Alice's tie the finals with one of the most incredible comebacks in NBA Finals history a great game and I love down the stretch they put the ball in their best players hands and Dirk Nowitzki did not settle for jump shot floor at the Garden in Boston Isiah Thomas consoled by his close friend Avery Bradley still trying to cope with the tragic loss of his 22-year old sister Chyna just yesterday they had a moment of silence here at the garden and tears streaming down the face of Isaiah Thomas he will play and moments ago he was introduced to the home crowd",
    "and Bradley had Lopez closing out I'm paying about a 29th footer Vikas Fred Hoiberg time [Applause] a basket equals a 50-point games Kobe attorney I am having a third loan have you never seen to get tired corner of the team he's done we'll be with the ball and the linkers downfall [Music] on its way but he continues to leave the ball with half a minute to play bright for the [Applause] he is fouled but if he have enough colege the get free-throws will save two free-throws per 60 [Applause] a 60 point game final seconds here at Oracle Arena",
    "it's official number 73 the greatest regular season in NBA history now belongs to the 2016 Golden State Warriors [Applause] [Music] [Applause] Isiah Thomas is hurt down on the court underneath the basket I couldn't tell what happened and this is a tough one holding his right ankle Billy my captain our the trainer is with him and and the Pistons are going to have to call a timeout because Isiah started to get up he got up and then went down on the floor then I say is coming back in the ballgame it's been the Isiah Thomas show plus an injury to Thomas here in the third Thomas off balance basket counts and a foul",
    "as he goes into the first row and he is still limping he is a game performer he's got to be hurting and limping and he continues to put the points on the board for Detroit Isiah Thomas has put on a brilliant exhibition of shooting this Mike ankle injury in this third quarter he has been a one-man gang dream attempt remaining in this period Thomas and a looper Isaiah's shooting eyes still on he has 16 points in the corner 28 in the game yeah but he's limping noticeably right now and Isaiah Thomas coming period he has 35 in the game 23 in this period can you imagine the great performance maybe one of the best we've ever seen in",
    "one quarter in NBA Finals history our test looking gets you the pride fly until you has to put up with the buzzer [Applause] [Music] [Music] Michael hit traffic touch bro [Applause] [Music] inbound at half-court [Applause] [Music] Utah Jazz to the NBA Finals moment ever break down defensively nobody stays with Stockton Berkeley has to come out [Applause] coming up on a minute remaining here in Game five Pierce four three let's go Paul pairs from way downtown then Boston leads by four big three-pointers here the fourth quarter gets it the Oakley Park by Horace bounces Meyers cross-court sca",
    "comes the plane is there a foul on the play no it but the passion look at the animation on Tracy McGrady normally sweep the eye very smooth you don't see this kind of energy and passion david aldridge talked about hits playoff time look at the extension Sean [Applause] itself let me give you a little quote that Jeff Van Gundy goes by six [Applause] [Music] [Applause] kevin is asleep check if he's hurt check if he's here he's hurt not showing his feelings are hurt down-low predominate baseline drive [Applause] that fantastic Dark Soul all control good rebound nice outlet on the",
    "run two on one three the finish because been to make that a mobile pitch and finished he caught it watered down way up and down knocked away in stolen years Middleton Yanis trailing the lock [Applause] double team three on the 24-second clock it's going away from Charles Smith and Payton safely [Applause] [Music] [Applause] Sonic's baton saving the ball did he get it yes he does right into his teammate Sam we'll take another look at what a play by copy pasted some lettuces improve pass in the empty Davis over there very close to a five-second count Davis at the buzzer and the pelicans defeat",
    "the Thunder what the ruling on the floor is a made basket by Davis [Laughter] [Applause] [Music] [Applause] Aaron Gordon again chef Levine championship round in the Verizon slant on those honey want on these this is real this is real okay this is real this is real [Music] [Applause] okay Zach said that's it but we'll just to say f9 that's not so good it wasn't ten the dinosaur Play you can go to Orlando Florida that might be helpful Peyton in that mascot [Applause] [Applause] my god let's go home let's go",
    "that's pretty bad I can't I just don't know man wait wait wait let me see [Applause] like that solve in Arizona I saw him in there Lando but I don't I don't see this well that's why I picked them kidding man [Applause] [Music] [Applause] always this is a time this is a time you [Applause] don't know what you saw if you see it in slow motion hey man you would know what you just saw a man you would know what you just saw bring in the ball no watch out lowly breathing a bit behind his head first Reggie Watts he",
    "cocked it behind his head like he was going to tomahawk [Applause] yeah nobody lost them that was an incredible display shooting Wow [Applause] [Music] was turned off but whether what he's going to try to do is blow out the candle as he dunks are you kidding me you gonna do is make a mess hey Kevin remember the last two years of the slam dunk when we said that slam dunk contest was back yep look this is what we're talking about validating it right now right now he's gonna blow to kill Chuck if he blows the candle out you gotta give away he's only us at TT hazard now he goes up then it's",
    "still out he takes the ball [Music] he could jump over Superman he said again Jamie if he can jump over suit than I had to get on my feet the world man changing with it come on seriously if he can jump on my seat man come on to the side look at the run look at the left hand [Applause] pretty good right it's good okay [Applause] I told you ja wohl it's gonna get it dance it out baby dance it out rock it out yeah I was upset he didn't get at that time and Grady bumps [Applause] for his name Rob said coming over that's a clean block block it kitchen",
    "after the fact the jog out to Lin Lin to Shepherd shepherd pull-up jump shot back to whoa coach Aaron rebound now the next will hold it for the final shot as a 24-second clock is shut off Mike day 21 Paul timeout and let the Raptors set up the D the crowd on its feet here at the Air Canada Centre [Applause] they had the Lakers down Kobe with the dagger and now Lin shop Westbrook call the depot single to inbound grant and Adams on the floor for the Thunder [Music] flutters out of timeouts Adams gives it back to raw speed shy John historic day all I can say is why not 22 triple doubles on the",
    "season and he is the ball game like that [Applause] [Music] [Applause] [Music] turn best in the league and finishing [Applause] [Applause] 207 three [Applause] Wayne Wayne now you see me [Applause] kevin garnett simply a spectacular move by flash here's James drives past Bentley [Applause] he blocked me jumpshot in the guard all five nine of them that's what it was with the Knicks against the Rockets with this one against the four-time MVP post a hammer good job baby got the rebound Rose it out to pole sitter we said no believe that fortunate you",
    "know Mike Paul shot up the shot clocks it'll reset and head reset [Applause] [Music] was that is gonna be crazy I like this oh you got it [Applause] [Applause] there's the switcheroo desire now watch Kent Bazemore come into the picture though he's got time something's with 67 points with 645 remaining Tatum drives down that strong sit down Wow LeBron James so he finishes it and then he goes right up to him a thorough rookie with 24 was Shawn Marion on him their best defender will see how the Thunder plan Sefolosha throw in [Applause] when he gets his",
    "legs into his shot his mechanics are excellent right oh my goodness diving stop by letter / play / play all my goodness what a tremendous play did not give up on a play chases him off the line I was alter the shot Minnesota's shot blocking his gotten so much better Brow's top job but he makes the Shelly's playing well for Sacramento 21 points for belly last night Rose playing really well for the temple walls in the starting not here tonight is that perfect though lovely I need more cowbell but the anchorman as well Tara 124 in that vault lobs to the Warriors way the tip walls all fences Roland's they've got a chance to hook that here that",
    "ryptonite Rose gets inside puts up with tough shot and hits it anyway forty eggs fifteen a half a century for Derrick Rose here tonight to have a game like this 50 points against a good team three no long rebound tracked down by Rubio Engels will fire for three that won't drop another rebound Exim has it blocked in the corner by who else tell it 2011 MVP rose and everybody just streams out on the floor to greet him showing the respect [Applause] [Applause] they're called anthem ants mice got the double ticket touji like playing against the Lakers curry has not scored in this game his first basket sit straight 47:44 he's",
    "like no Audrey Krispies and he hits another long ball that's his fourth of the first half here comes Collison kinks out Caspi well turn this breakfast systems on Oh Bree Casspi is on fire and again the Kings can't come up with a rebound and it's right in their midst and a custom pretty boy Wow how does that happen Porsches too many shots now I really have a good chance to pick it out there 403 by step and it's fifty three fifty there's a heatset people coming over test me oh boy he has now made six threes and eight fries and it's 5650 he's got 23 here in the half curry",
    "did try to answer back like NBA basketball here's test me why not he's got smoked took it off his fingertips overreach me [Applause] let him bat it back when it's curved Tori have to crawl see and getting the basketball because a lot of good things will happen that just wasn't scoring [Applause] in downtown in a different way to score coming off baselines man oh he does it again throws it right up on the rim James comes flying in from the right corner and another dunk it was a dunk athan Friday night they're starting it again here this afternoon boy left wide open incredible rebound put back John Vincent glass goes Wow",
    "poor pal huh Kapow Butler now in the rage close to the screen t-man Gameboy ripman explodes on Gasol the nice pass by Butler slow rotation by Gasol and if because if Griffin is able to get to that launching and got down there to tell as a set it stayed off that rim but he was Hornswoggle befuddled c.j but countless season-high with 32 and the Blazers leave it by 14 19 in the corner from our largest lead here of the night I don't feel right watching this I don't feel right watching it and enjoying this that is inhumane in the Barrett [Music] [Applause] Brown the Griff",
    "ins frantic video by one of mine he stopped about three feet short of the rim and just threw it down that is amazing he never touched the rim with his hands oh my lit up with Lorna Murray James just got the kid who's the piece big old black by Jared Allen all of them Parker the Neal for the shoot marking homes read the beat all of Blackford James throws it back it's Twitter ready to dunk here here in Game two and here one of the great blocks you will ever see splitter winding up to throw it down and the strength of LeBron James to stop this and throw it back exquisite timing [Applause] [Applause] on his back how did",
    "he see him there well his name is Jason Williams that's why coming off here by one Simmons gets it into howís [Applause] [Music] Parker on the drive nearly lost its still juggling Parker with two to shoot just gets it off the time any banks a man what a shot from Parker stink 2.6 seconds to go now late Griffin will turn [Applause] there here it is again we're gonna watch it right Griffin oh he steps behind holy sculpture becoming something very very special Rondon with the fake paul what a beauty [Applause] [Music] [Applause] and Rashid from long way",
    "it's Horford across the lane where their eyes are always looking around this a nice lunge and steel bike puntas selected this young man with the fourth overall pick the nice little spin move and finish in transition here he's a work in progress and needs to put on some weight [Music] [Applause] that was up that pass to the most high Jordan gets the step on down so first offensive rebounds two waves finding an open area inside drives hard draws terrific now watch how he splits the seam of the zone all right and then he comes right up there saying moving underneath on the shot and then the finish how about the finish",
    "a flip back with the English on the on the spin of the ball cargo exploded showcasing a little bit of everything and then some feedback the man I saw a plea lane to the basket so I was going to dunk the ball I exposed the ball but then I saw long arm Sam Perkins there and it was just instinct to change it I changed it to my left hand and with able get it off [Applause] Partin just crossed over West Johnson take a look me to have this man down Lou Johnson this can go up 14 Jordan Pat Petrovich oh yes yes yes six points for Dallas came back Nikki out with a nice boom six tenths of a second ransom over",
    "Gaza nice that's it's buries a three out of the corner can you believe that [Applause] [Music] since the feet left his hands before the clock struck double zero crossover Mitchell into a and when you've gotta come in oh my goodness we talked about the struggles of Mitchell shooting the basketball but he [Applause] [Applause] we've lost the handle pops it up right - Jason Williams Williams crisis over loses Gary dragged into the lane Burke's the hymen off the window up and end what a move by Jason Williams past records suddenly caught me looking lemon biceps elosha just wouldn't quite fall now here's Crawford the other",
    "the word bull Wow terrific game for Crawford and they take the lead he's got 15 points no luck Rondo behind the back for two put it in the pot baby put it on the real foul to give for Houston 9/10 left of three wins the series its lured he got the shut off for the first time 814 because it goes in at triple zero but it's out it's over and the Portland Strip [Applause] a one-point game [Applause] welcome to tippet Bryant with the sale [Music] [Applause] here they go they get it to Fisher [Applause] the buzzer",
    "it'll have to be reviewed they'll review it they'll review it it's also it's so close very close what's the Louisville has to be out of his hands both it's out of his hands it's out of his hands Wow that's good ready five seconds to go continues to hint at the line [Music] my SEP rockets with a quick jog going is all over the Grady I was picked up [Applause] and Marik can't find anybody they have no timeouts when Annie finally gets it in to the grading eleven yelling on the inbounds rata make things difficult for Brett fire he gets it in [Applause] we which is felt on",
    "the floor and it took approximately [Applause] [Music] [Applause] here's Iverson move it offender stays right where the Allen wants to go watch the baseline [Music] nine in a row seven straight points five give a for some survived Caritas behind [Applause] it's the largest that could be the greatest move I've ever seen that no I'm being serious watch his head coach no we're gonna show the reaction of Steve Kerr as this play was developing for somebody else [Applause] if you make a move with him right now to try and get they probably could use like their athletic [Applause] shot clock Johnson",
    "takes it now is like a poker there but among games the flute played it just 16 seconds left to play Derek one-on-one at the top starts he just crossed over watch this watch Miller can't get up bobbin and I can't get up [Applause] [Music] [Applause] turning around and around like a top st. Francis playing on the show won again by Stevie franchise slight jabbar slight jump hook to wrap right around Kathir [Applause] he looks like urban and this was more like a nice man move right here I don't know somehow kisses it off the glass a little top loses it all right go visit",
    "perfect last-second decides to go over some people to come over tonight we love it he's got 13 and a chance for a three-point play well we're down at ten seconds remaining in overtime and Michael has the ball again guarded by Shawn Marion the fadeaway [Applause] it's just different than East up to point please as we see Michael takes the anyway [Applause] [Applause] Celtics have to push it look for the pick-and-roll is someone to the corner not a seven-second there's a doctor stuck here's a welcome [Applause] eople the Warriors heat need a 3-2 win 10 seconds",
    "1 raid against Iguodala 5 seconds well waiters back to twin shoots no I couldn't get it off now fires it up [Applause] 1:26 go to 20 [Applause] just happens gonna count it up in time let's take a closer look here on your street totally off Baptist pufta class circus shot and weighed the hero once again and bragged to his coach about taking MJ and know he'd finally get his chance when I grabbed a ball I heard Phil Jackson yell Mike I gave him a little cross to see what he bite on him I let him set his feet then I stabbed it back again ",
    "Mor behind the back Bane steps back Mor ball fake oh oh my gosh people watch millions and millions are going to watch this also Lamela has baz on him what was that way they wanted to look at this look at the dance right here T's like okay will you shoot I'm tired of getting embarrassed on the perimeter Keon George runs into Luca LCA on the floor FS Kyrie Fant what way to finish that hustle [Applause] play on a platter for Jones to climb the ladder but Jazz with a [Applause] turnover nasty I mean that's all you can say about it and Collins shaking up and I think also walking to the locker room Edwards",
    "hurt himself he's holding the right forearm doin will defend Curry a screen by Green the switch to rivaly three C oh oh run here he got the switch that he wanted he got Lively dancing te 109 the foul called to McDaniels a minute 10 to go timer is down to five donic can't find any Space 3 seconds two deep one donic oh my gosh boo gets it back dodic Dums inside Washington puts it in two seconds left the Cavs are out of timeouts they have to go 94 ft stru from midc Court oh oh do you believe this wa to take a shot of this James against Porter Drive Spence gets inside it",
    "good it's 40,000 for LeBron James the NBA's alltime leading score with another Milestone as the legend of LeBron continues to [Applause] grow Mor off the bounds 360 spin in the Finish oh he did that oh no 360 spin and a finish for jiren morand spins and hits again I'm morand you run out of words to describe what he can do go for the crank and then spins off the back iron and off Horford into Victory he's ahead of the pack he just puts it over there White's head and he throws it down like he was teasing him with the ball he did he held it up there like he was playing",
    "against sixth graders rebound of Del r del r eight points in 13 minutes hero for Caleb by that pitch ahead pass to Tyler hero one fake two fake drop off D behind both Dam and CJ here he comes up the floor his rookie ear he had just 10 threes oh Collins 8year Pro watch this one oh man you know got to be strategic you only get six so that's it KD with a crossover Glides right to the basket just how quickly he gets off the ground I mean there's so many aspects Marshall lobing it up oh my Zion Williamson giving Barkley Center a highlight to remember oh like that shot clock about to expire that's able to track down",
    "long rebound and Simmons Simmons misses the bunny and the older son made it right back the younger son RI through his leg H behind his back like that like that how about about that pis bringing the house down okay T wow fun game here in the Twin Cities look at the moves by Edwards swash and slamming Anthony Edwards SK are you kidding me man play it's loose Yannis has got it Brunson from behind yanis wow dropping in the sledgehammer and Kevin Giannis took one dribble from gets it into capella hand off to Trey tre's going to back it out we're down to 16 Hawks trying to win it not give the Lakers a chance back to Hunter back to",
    "Trey he'll take the three b game Trey backing it out wanted to work some clock Hunter covered up by Davis got it right back to it and Trey drills the biggest shot of the night shot clock game clock shot clock down to five here's towns from three it's gone Carl Anthony towns with the dagger 3point field goal and an it's lead by five 36 a minute remaining in this game Luca gets through the Defenders Powers up score it 72 for number 77 once he split the D it was all over I love it don't call it tie ball game worst can happen we go to overtime Murray makes a move d the nuggets have won 5 Seconds to",
    "work with even at 90 Steph from Freemont yes sir pick and rolls as well and this is the shot it's a few steps Beyond half court but he's got that type of range he is one of one time here 2.8 It's Quickly in to Luca and he got it away from about 40 ft he made it he made it he made it a little something for Slovenian Heritage night Morant trying to feed it ball to the floor job from the seat of his pants L look at thisle he's waiting he's waiting for the right pass 5.2 left no timeouts left for the buks Here Comes St 3 seconds D PS for the",
    "Dave time is alive Dame time gety looking looking inside the pass jump shot is up it's good with 1.8 remaining G as Alexander Nails it and the Thunder go up by one get some points out of this oh gy from the back side he was on his back still get the shot up to beat the scrip on San Antonio from down 15 to in front by 14 and ding in the P spectacular stop it stop it Kai two and look at them guard one another trying to poke it away uh-oh uhoh wa right back right didn't I say you learned it for me you watched The Telecast oh Kyrie [Applause] Irving and",
    "Murray with the steal here at 3/4 cour yic has it clock ticks got to put one up yic for the win in your best players hands I just told Michael Malone it was a great play call nice Denver quter at the other end and he tries and he gets it to go beating the clock cord length that's intercepted Murray good at the go he's got it got it got it a big time three oh what a shot right when Minnesota had this in single digits and in those six wins he's averaging 37 a game he's got 35 now oh no no no no no no you got to go he's he's this is about as H as",
    "we've seen no way it's like a game of horse out there no way and Jabari in for Irving Irving for the win oh my a southp finish from Kyrie Irving just absurd T to shoot Edwards oh Edwards a signature slam now mbid takes on hardenstein Maxi for three he got it Tyrese Maxi out of the pack T chenzo finds Brunson great defense here by the Sixers wison gets a prayer of a bounce two-point game Maxi hits the deck hard takes it from him shot clock is off D chenzo no hardenstein with an offensive rebound another chance here Devon chenzo he's got it the Knicks have the lead again",
    "Lakers out and running L for LeBron James and even cam reddish was here LCA Kyrie for three for three and Dallas lead almost lost the handle kcp falling off the cliff turn it over Tatum on the move oh he set off the smoke detector t spins it up no batt it off of the rim here go the Pelicans 6 seconds to go Zion Williamson he's scores with 3.8 and New Orleans has the lead that was sketchy there the ball was on five fouls so Kai's going to have a go right at him wow exquisit that's incredible nobody in this game can do the special [Applause] thing and",
    "my goodness it down on him and he's going to get called for tating taunting after stuffed when he played for the Sixers that knocked us out of the playing game right yep oh Wy nice touch as he rolls it off the iron and good he's having himself quite a game right now Focus cuz we got too hung up in the officials he talked about some immaturity oh DK Jones D that gets the crowd fired up he throws it down shot clock is off wiama goes right by [Applause] Durant with the left hand oh look at and look at KD's face Russell gets past lard with seven floer good Russell gives the Lakers a one-point",
    "lead with 5.9 remaining AG a lot of guys on the executive committee are deeper in their careers they're in their 30s but to see Jared whoa Zer Williamson with the dunk against [Applause] Jackson canar a catch and shoot California a sord tops twin brother of a men Thompson what a move oh Duncan Robinson a screw ball for the layup what a dribble move get that reverse great y Steel by sus he's got Anthony Cole with the one-handed dun that brings the clowd to its feet six Reeves going behind the back spinning away from the glofin the crowd loves it Reeves putting on a show with the fancy dribble",
    "luck down to five Bridges got he was close to it chance for the last shot goodness ball mov but right here Drew have you ever seen a a live dead body there's one right there green isoing green driving Green dunking to five Klay tops it at three clay for the win good I told you play Thompson is still out there if you want to take step away they got another killer advantage Smith oh my blocked by Wy Again by Wy get it out of here P the ball Johnson on the drive and he's fouled landale Point landale leads the break here's the lob and that time actually Jabar he gets a bit of that it goes up the backboard",
    "and jayen 18 points for Shaden sharp and the C out is 1054 99 but just for a moment as shark goes back so far tap by LeBron D going to give it up throw it down little Showtime ah that was nice LeBron Taps it gives it to B head oh my God denied by Keon foxy in trans theck connection oh my [Applause] God this build getting some early minutes here Taj Gibson on the floor as well and pal open Luca donic with a little spice 4 seconds got it from CBA again late in the clock in desperation he faks it up is luk right there I got to go so a",
    "new lineup Dr in the steel oh the big cat take it time big cat oh Dr in crossed over Chad wait T shoes CH T you shoes the big cat with the crossover woohoooo oh he's got the everything oh my goodness no no no he made it he CED and made it on a tough turnar around Demar D roen gets it Baseline and is able to knock it down Chris and we go to over defense forcing the Miss and the crossover winding up and brings the [Music] boom on one 6 seconds Jaren Jackson Jr two seconds 1.2 on the clock Memphis for the two-point lead [Applause] blocked by Victor got be",
    "another word for that one destroyed oh mama talk about destroy vict for w Yama what the and in those six wins he's averaging 37 a game he's got 35 now oh no no no no no no you got to go he's he's this is about as no way seen no way no way it's like a game of horse out there no way and Jabari knocked down against durin loose ball to duumu shot clock down to two D Ro in it the marvelous the rose and Compton finest with some Hang Time defensive players as far as stealing the basketball in the league oh seaka one hand Rising jam and he knocks down two leg Brandon vill with a move",
    "and throws it down man we are seeing some offense here yeah when you talk about Joel NB oh nice finish a poster from o and the foul but they are shorthanded and it has been a rough season a drops bade and hits the [Applause] jumper that was a beautiful Caruso Alex Caruso to TI again big to play big big time plays turn the AC up cuz he's hot up against Brooks goes away from the pick we his way to the C in the hole on jaari Smith that's a poster Here Comes Collins G screen domas give me that the hammer yeah yeah de Joe and hren The Most Dangerous Ones gidy looking looking hen's got",
    "it turns fires he hit it he was on the line though I think he might have been on the line so it went to 0 they got to review it it automatically goes to review they have to get this ball inbounded they're out of timeouts they throw it to grant grant runs up for three look at it tight up and he baked it in he banked it in oh God you saw that coming dick Life Special wow got it back and that Home Three what what was that three he trying to find zubot such good play by ad LeBron train down the track look out bling foul that's a three-point attempt Look Out Below look get on top of",
    "a good Outlet goes to Russell oh what a play by do oh now you see it now you don't put a little get some points out of this oh gy from the back side he was on his back still gets the shot up to beat the two and look at them guard one another trying to poke it away uhoh uhoh wa right back right didn't I say that pops upset vel's going to have to go on his own three-pointer no good Wim Bama eight to go you might want to call a timeout to advance it Johnson takes it from him Johnson hangs yes and the Spurs have the lead a lot pressur it a three will tie",
    "it and hand off to Luca back to XOne got they did it they did [Applause] it the basket he throws it up and misses tapped around it's loci and they're going to get control of it oh thebr look out game over wow you see that speed he thought he was F seaka makes the catch goes to knin boy the pace will somehow hang on on it oh turns into a dunk by Turner and Moy gets called for the block and Turner has a chance for the three-point play 71% as Sherman Hamilton mentioned and you have players like Ingram no be with the throw down he had this that I mean there's so many aspects Marshall Robin",
    "up oh my Zion Williamson giving Barkley Center a highlight to remember this draft you decide not to look for somebody that as Dave leer really wants to show this so we're going to do it right here watch it between the legs in the slam dunk guys though win or lose Jackson Davis oh over Victor wama to joic from the free throw line Jones has it 5 Seconds To Go deatte gram yes spur get it's a good one back to Booker Booker on the drive Booker puts up a three oh he puts it in with and you see well I got to get it off just throw it up there same spot that Jimmy Butler missed the other night here the fourth quarter yeah",
    "have Booker came into this game the other way and reads in the way oh what a pass what a watch this pass this is unbelievable one two three five Defenders look at that that's amazing Point Deonte George runs into Luca Luca on the floor finds KY re fastic what a way to finish that hustle play on a platter for Jones to climb the ladder but after KY looking looking inside the pass jump shot is up it's good with 1.8 remaining gildas Alexander Nails it and the Thunder go up by one right in front of their bench AB going Coast to Coast they'll throw up a prayer got it wow what a [Applause] game",
    "so y they got to be careful here these guys dis is switching now you can garish the sky hook which so rare players do it but now we got Fox on the break Fox pick dun's pocket and Malik Monk got this Crow low block he'll come off a yanis screen and get it near Mid court with 5 Seconds lard step back blocked by did winning loose ball game over huge win for the Lakers without James and an injured Davis they win it 1231 Wiggins with five fouls monk drives on him monk hangs and he scores what a basket Malik monk gives the Kings the lead it clock ticks Curry guy to come off of the handoff",
    "de to the rim the shake and the bake push the shot clock is dark they're down by two George wants it all the three oh my goodness hot damn Paul George push the Clippers out in front by one doic into Jackson hay what a pass some three go what what a pass how did he get that through all those defenders in two seconds left Butler step back for the win yes Jimmy Butler delivers the victory 118 [Applause] 116 here's jayen green going oh with the left [Applause] hand he's got 24 Rocket's down seven Trey the floor is spread it's holiday it's Murray from the top good with one1 of",
    "a second and the Hawks going in front 123 to 122 I can't believe it point four Quinn says play on Murray 3 seconds two DJ for the win got it yes yes coming out of the timeout here's Kobe white goes around the world and punches it home over Harrison Barnes Kobe white slowly breaking out four early assists billian also has four assists Edward to the basket skies and jam nothing wrong with his knee whoa what's wrong with his knee George fine give me some tenden ntis team with a chance to win it in his return here goes Moran he spins morance scores and the timer expires K the basket and John morance wins it for the Grizzlies",
    "12 for Middleton REM Bama oh goes back oh no and puts it down are you kidding me come on you hook again well here's the oldest guy in the league right here spinning underneath oh LeBron a 360 oh the old man did a 360 wow Hawks could tie it with a two or win it with a three Here Comes Murray a three for the lead he made it with two seconds left do jant Murray puts Atlanta up 109 to 108 range look how far away he is from the basket on this pullup find seaka their Leader scri by Caruso final seconds LaVine can tie it Zack LaVine peruso for the lead turn up the",
    "a is CED here woo woo big play guarding green here's Jaylen oh what a circus move by Jaylen green oh man so creative in the air oh pel just missed the steel McDaniels can't make you pay but Edwards follows up [Music] goodness Lord that was filthy I don't know seconds now five now four up fake from the Baseline knocks it down with Vana who was ice cold all night just warm enough here down in Georgia turnover time taken by Johnson he's going to go all the way and throw it down and one wow what a way to start the game for Atlanta nerk with the rock finds Durant raising up for the win but watch this",
    "watch guso he made him change it in the air and then knock it down oh man two on one on the break Isaiah Joe SES it up green throws it [Applause] down Harden this is for the lead oh he put it in counted at a foul oh my goodness AJ Green little tough floater oh W Andre Jackson Jr okay did he fun game here in the Twin Cities look at the moves by Edwards swash B and slamming Anthony Edwards SK are you for three off the rim 6 seconds five Rosier to four Court 2 seconds one bam out of Bio from the top and he triples bam out of Bio with an improving three-point shot I think he got",
    "it away in plenty of time that was his first triple try posterized tler denied up top oh ju yes they do B look at that spinning like a top pass great finish Collins SE Curry comes free gets the ball puts up a three-pointer B Steph Curry Nails the three-pointer with 710 of a second remaining seven to shoot for George three to shoot gets down lets it far for the lead God damn Clippers lead by [Applause] two top good comes up there to by him the pass though to intercepted oh cocking rocking and knocking it down and landed with a pose is Jay to give Minnesota a three-point lead he missed it Pacers are not going with a timeout",
    "they Advance the ball n Smith lays it up oh man a defensive play as n Smith was trying to get to the rim they block it Minnesota wins it 113 111 the Pacers have a shot blocked at the point2 left no timeouts left for the bucks Here Comes D 3 seconds dve PS for the Dave time is Alive and Well in [Applause] Milwaukee oh uhoh he just lost Butler yeah Jaylen green and the Look Away you're a wizard Jaylen green oh my goodness yic has it clock ticks got to put one up yic for the win oh it's goodone yic got it off in time and the Nuggets win it are you",
    "kidding me easy CA has that tip by moley but dodis gets it back dodet dumps inside Washington puts it in 2 seconds left the Cavs are out of timeouts they have to go 94 ft stru from midcourt oh do you believe this you believe that your final score here tonight your Cleveland [Applause] Cavaliers just sit back and enjoy tap another turnover for Utah Edwards gets it back and threw it down and one from the Raptors oh my god ANS HT his hand on that too that was ridiculous IA looking in for Irving Irving for the win oh my oh my a southp finish from Kyrie Irving just absurd",
]

highlight_embeddings = np.array([vectorize_text(text) for text in highlight_texts]).astype("float32")
index = faiss.IndexFlatL2(384)  # Using L2 distance
index.add(highlight_embeddings)
faiss.write_index(index, DB_PATH)